let products = [
  {
    id: 1001,
    subject: "Subject:Math",
    location: "Location:London",
    price: "£400",
    image: "Images/maths.png",
    Spaces: 9,
    rating: 4,
  },

  {
    id: 1002,
    subject: "Subject:Algebra",
    location: "Location:Oxford",
    price: "£600",
    image: "Images/maths2.png",
    Spaces: 7,
    rating: 1,
  },
  {
    id: 1003,
    subject: "Subject:English",
    location: "Location:Dubai",
    price: "£100",
    image: "Images/english.png",
    Spaces: 14,
    rating: 2,
  },
  {
    id: 1004,
    subject: "Subject:English Literature",
    location: "Location:York",
    price: "£180",
    image: "Images/english2.png",
    Spaces: 10,
    rating: 5,
  },
  {
    id: 1005,
    subject: "Subject:Music",
    location: "Location:Bristol",
    price: "£900",
    image: "Images/music2.png",
    Spaces: 10,
    rating: 4,
  },
  {
    id: 1006,
    subject: "Subject:History",
    location: "Location:Scotland",
    price: "£500",
    image: "Images/music2.png",
    Spaces: 12,
    rating: 3,
  },
  {
    id: 1007,
    subject: "Subject:Computer Science",
    location: "Location:Barcelona",
    price: "£700",
    image: "Images/music2.png",
    Spaces: 7,
    rating: 3,
  },
  {
    id: 1008,
    subject: "Subject:Drama",
    location: "Location:Delhi",
    price: "£890",
    image: "Images/music2.png",
    Spaces: 7,
    rating: 5,
  },
  {
    id: 1009,
    subject: "Subject:Sports",
    location: "Location:Madrid",
    price: "£810",
    image: "Images/music2.png",
    Spaces: 9,
    rating: 3,
  },
  {
    id: 1010,
    subject: "Subject:Pscyology",
    location: "Location:Turkey",
    price: "£510",
    image: "Images/music2.png",
    Spaces: 11,
    rating: 5,
  },
];
